services:
  reliability-index-explorer:
    build:
      context: .
    image: reliability-index-explorer
    container_name:  reliability-index-explorer
    ports:
      - "3001:3001"
    restart: unless-stopped
